development:
  adapter: postgresql
  encoding: unicode
  database: db/testguru_development
  pool: 5
  timeout: 5000
  username: hwo
  password: hwo

test:
  adapter: postgresql
  encoding: unicode
  database: db/testguru_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: testguru_production
  pool: 5
  timeout: 5000
